✨ feat: user positions (#19)
* 🚧 WIP starting user roles

* 🧪 fix tests

* ✨ policy actions and model privilege check

* ♻️  add user service & improve policy and add seeders

* 🧪 unit and destroy user tests updated and fix register mod

* 🧪 register test and changed auth service register

* 🧪 add tests for user roles and create index and store for user

diff --git a/run b/run
--- a/run
+++ b/run
@@ -27,6 +27,14 @@ function setup {
   gen_key || echo "[warn] Key generation failed (gen_key); continuing..."
 
   migrate || echo "[warn] Migrations failed (migrate); continuing..."
+
+  seed || echo "[warn] Seeding failed (seed); continuing..."
+}
+
+function seed {
+  source .env
+  echo ">> Seeding database..."
+  docker compose exec app php artisan db:seed --force
 }
 
 function phpstan {
@@ -50,6 +58,16 @@ function phpcbf {
   fi
 }
 
+function test {
+  docker compose exec app php artisan test
+}
+
+function all-tests {
+  set -e
+  ./run test
+  ./run phpcs
+  ./run phpstan
+}
 
 function ps {
   docker compose ps
@@ -87,6 +105,7 @@ function composer {
 function rm-all {
   echo ">> Cleaning up .env, vendor, containers, images, and volumes..."
 
+  rm -rf pgdata 2>/dev/null || echo "pgdata directory not found, skipping removal"
   rm -rf vendor 2>/dev/null || echo "vendor directory not found, skipping removal"
   rm -f .env 2>/dev/null || echo ".env not found, skipping removal"
 
@@ -98,7 +117,6 @@ function rm-all {
 
   echo ">> Cleanup completed!"
 }
-
 
 function exec {
   source .env
