♻️  add user service & improve policy and add seeders

diff --git a/run b/run
--- a/run
+++ b/run
@@ -27,6 +27,14 @@ function setup {
   gen_key || echo "[warn] Key generation failed (gen_key); continuing..."
 
   migrate || echo "[warn] Migrations failed (migrate); continuing..."
+
+  seed || echo "[warn] Seeding failed (seed); continuing..."
+}
+
+function seed {
+  source .env
+  echo ">> Seeding database..."
+  docker compose exec app php artisan db:seed --force
 }
 
 function phpstan {
@@ -55,6 +63,7 @@ function test {
 }
 
 function all-tests {
+  set -e
   ./run test
   ./run phpcs
   ./run phpstan
@@ -96,6 +105,7 @@ function composer {
 function rm-all {
   echo ">> Cleaning up .env, vendor, containers, images, and volumes..."
 
+  rm -rf pgdata 2>/dev/null || echo "pgdata directory not found, skipping removal"
   rm -rf vendor 2>/dev/null || echo "vendor directory not found, skipping removal"
   rm -f .env 2>/dev/null || echo ".env not found, skipping removal"
 
